In [6]:
import numpy as np
 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,1,1],[2,2,2]])

print(a)
print(b)

print("Addition:\n" ,a+b)
print("Dot product:\n" , np.dot(a ,b.T))
print("mean of a:\n" , np.mean(a))
print("mean of b:\n" , np.mean(b))




[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [2 2 2]]
Addition:
 [[2 3 4]
 [6 7 8]]
Dot product:
 [[ 6 12]
 [15 30]]
mean of a:
 3.5
mean of b:
 1.5
