In [ ]:
import numpy as np
 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,1,1],[2,2,2]])

print(a)
print(b)

print("Addition:\n" ,a+b)
print("Dot product:\n" , np.dot(a ,b.T))
print("mean of a:\n" , np.mean(a))
print("mean of b:\n" , np.mean(b))




Addition:
 [[2 3 4]
 [6 7 8]]
Dot product:
 [[ 6 12]
 [15 30]]
